on: 
  workflow_dispatch:
    inputs:
      tag_number:
        description: 'the tag number'
        required: false

jobs:
  build:
    name: Trigger received to Run Benchmark 
    runs-on: ubuntu-latest
    steps:
      - name: Run Benchmark
        run: |
          echo "Run Benchmark"
          echo "Env: ${{ github.event.inputs.tag_number }}" 
